from . import bxi_line_of_business
from . import res_company
from . import res_config_settings
from . import salary_advance
from . import salary_advance_installment
from . import hr_employee
from . import hr_payslip
from . import employee_resignation
from . import sign_request
