from . import configuration
from . import res_partner
from . import hr_employee
from . import approval
from . import gift_request
from . import gift_receipt
from . import donation
from . import sponsorship
from . import due_diligence
from . import extortion
from . import violation
from . import hr_expense
from . import res_config_settings
